### ISSUE TITLE
Frontend StyleGuide

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#210]
We should change some things in the frontend to completly meet the official Angular StyleGuide.

- [x] [Core Feature Module for Services only](https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-11)
- [ ] [Move logic to service](https://angular.io/docs/ts/latest/guide/style-guide.html#05-15) (especially task component)
- [x] [remove on on EventEmitters](https://angular.io/docs/ts/latest/guide/style-guide.html#05-16)
- [x] [Look at that](https://angular.io/docs/ts/latest/guide/style-guide.html#06-03)
