### ISSUE TITLE
delivery of tests, 22.11.16

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#48]
We have to deliver the first part of the dokumentation next tuesday.

Because of this we need to put some extra effort into the dokumentation.

I tried to make a list with the things we have to get done until then:

- [x] Write unittests for the API endpoints
- [x] Reformulate the testconcept and write it into the realisation-report (Realisierungsbericht)
- [x] Adapt all of it to the wishes of mister Walter

**Comment by needToRoll** [comment]
Ok we have delivered all the stuff
The rest falls under the documentation epic.
